[package]
name = "graph-enumeration"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
petgraph = "0.8.1"
serde = { version="1.0.219", features=["derive"]}
serde_json = "1.0.140"
